### ISSUE TITLE
Is it possible to make a way to do the inverse?

### ISSUE THREAD

**Issue by furtabs** [MaxNeedsSnacks/FTBQImporter#11]
Not sure to ask here or BQ so I’ll ask both places but I really like the UI of BQ but FTBQ is super easy to code on. How easy would it be to take your mod and reverse all the functions port FTB Quests to Better Questing Quests. How feasible would this be?

**Comment by MaxNeedsSnacks** [comment]
BQ standard expansion already has an integrated importer iirc, that might be why your issue got closed there, as well ^^
