### ISSUE TITLE
Loot Chest Rewards are empty after import from Better Questing

### ISSUE THREAD

**Issue by chrisfand** [MaxNeedsSnacks/FTBQImporter#13]
Using a new install of Enigmatica 2 on MultiMC launcher. I installed FTBQImporter, and FTBQuests, while leaving Better Questing and BetterQuesting Standard Expansion installed.

Launched a new singleplayer world and ran: /ftbq_import quests -i -c -l -d

After a successful import message, I reloaded the world and completed a few quests, but every Random Reward Loot Chest was empty. The percentages listed in the tool tip are correctly imported though.

I restarted the modpack after removing BQ and BQ: SE, but the issue remained.

Here is a .zip file of all config files for both FTB Quests and Better Questing, which includes the "DefaultLoot.json". Not sure which file stores the loot rewards of the Common, Uncommon, etc. categories in FTB Quests.

[config.zip](https://github.com/MaxNeedsSnacks/FTBQImporter/files/4465659/config.zip)

Please let me know if you need any more files and I will provide them for you.

**Comment by MaxNeedsSnacks** [comment]
Could you try running the whole thing without `-l` and see whether that might change anything? I have a bad feeling about this flag in general and I honestly might just remove it until item group rewards are added to ftb quests

**Comment by MaxNeedsSnacks** [comment]
I think I found the issue, lemme try and push out a custom build for you to try

**Comment by MaxNeedsSnacks** [comment]
[libs.zip](https://github.com/MaxNeedsSnacks/FTBQImporter/files/4466219/libs.zip)

Here's the jars I built that worked in my testing environment (you don't need the sources one, I just zipped both of them up), not gonna lie if *this* is all it took to fix that that's gonna be a bit annoying for me, but oh well :p

Let me know whether this works!

**Comment by chrisfand** [comment]
Can confirm it worked, thank you!

**Comment by MaxNeedsSnacks** [comment]
Awesome, I'll push this fix out to CurseForge soon!
