### ISSUE TITLE
infinte crash

### ISSUE THREAD

**Issue by TheSoftDiamond** [MaxNeedsSnacks/FTBQImporter#14]
[crash-2020-07-13_09.59.16-server.txt](https://github.com/MaxNeedsSnacks/FTBQImporter/files/4913990/crash-2020-07-13_09.59.16-server.txt)
After importing quest from better questing I just get this crash, used ftbq importer.

**Comment by MaxNeedsSnacks** [comment]
As already discussed on Lat's discord, this was probably related to FTBQuests rather than my importer, so I'll be redirecting stuff to your issue there instead https://github.com/FTBTeam/FTB-Quests/issues/439

If it's confirmed that the importer is causing this, feel free to reopen!
