### ISSUE TITLE
Does not work for omnifactory

### ISSUE THREAD

**Issue by PORTB** [MaxNeedsSnacks/FTBQImporter#18]
When `/ftbq_import` quests` is run in a new world, the mod complains about having duplicate quests and orphaned quests. Upon relogging, the ftb quest book is missing many quests and also does not have the correct names/descriptions for any of the quests because a lang file is used for all the texts in better questing. The log file doesn't seem to have anything useful in it so I don't know what extra information to attach

**Comment by MaxNeedsSnacks** [comment]
Duplicate and orphaned quests are normal when working with Better Questing: Quests in FTB Quests are one-to-one and **always** tied to a chapter, while in BQ neither of those two conditions has to be fulfilled.

The fact that the book is *missing* some quests is a bit more problematic, can you send me a couple of examples of quests missing perhaps?

As for lang keys in names / descriptions, that's something I likely overlooked, but again, I'd appreciate the DefaultQuests.json attached as an example so I can hopefully implement this in the importer (for reference, FTB Quests can use lang keys like this `{this.is.a.lang.key}`)

**Comment by PORTB** [comment]
Better questing
(example 1)
![image](https://user-images.githubusercontent.com/34615701/114502302-eb1fd680-9c6e-11eb-9c3d-4156a74a6339.png)
(example 2)
![image](https://user-images.githubusercontent.com/34615701/114502682-83b65680-9c6f-11eb-989f-ad6281f7af5d.png)

FTB quests (imported)
(example 1)
![image](https://user-images.githubusercontent.com/34615701/114492734-822f6300-9c5c-11eb-805f-ac4c31027cc3.png)
(example 2)
![image](https://user-images.githubusercontent.com/34615701/114502725-9466cc80-9c6f-11eb-8bf0-9133f534a69f.png)


[DefaultQuests.zip](https://github.com/MaxNeedsSnacks/FTBQImporter/files/6301477/DefaultQuests.zip)

**Comment by MaxNeedsSnacks** [comment]
Yeah, so, I figured that this is the case, but from playing Omnifactory I remember most of these quests existing in other chapters as well, for example the upgrade kits in the early / mid game chapter. I'm assuming they used the n-to-m "linking" that Better Questing has there (fun fact, this is also probably why some quests are showing up that aren't visible in the BQ book). I *can* attempt to make that look nicer, but it **may** not work exactly the same as it has pre-import (since that is practically impossible).

As for lang keys, I'll check that out later, but again that hopefully shouldn't be as difficult to implement ^^

**Comment by TheAirBlow** [comment]
> Yeah, so, I figured that this is the case, but from playing Omnifactory I remember most of these quests existing in other chapters as well, for example the upgrade kits in the early / mid game chapter. I'm assuming they used the n-to-m "linking" that Better Questing has there (fun fact, this is also probably why some quests are showing up that aren't visible in the BQ book). I _can_ attempt to make that look nicer, but it **may** not work exactly the same as it has pre-import (since that is practically impossible).
> 
> As for lang keys, I'll check that out later, but again that hopefully shouldn't be as difficult to implement ^^

1) A lot of the quests are deleted because of circular dependencies (according to logs)
2) It is indeed very easy to do, I even made a small program to do everything. Basically, you should replace `%n` with `",\n"` (newline = new member in list), `"` with `\"`, `\` with `\\`.

**Comment by TheAirBlow** [comment]
@MaxNeedsSnacks please don't forget about existence of this project

**Comment by MaxNeedsSnacks** [comment]
Oh I didn't forget this exists, but honestly, with
- 1.12 being kind of a dead version for modding
- both the modding toolchains and the minecraft codebase being fundamentally different from newer versions
- BQ being a dead mod
- commands kinda sucking in 1.12
- FTBQ lacking a lot of functionality that would be required for a **full** conversion here
I don't think it's worth maintaining this project anymore, sorry
