### ISSUE TITLE
Issue with Importing

### ISSUE THREAD

**Issue by TheGoldCrayon** [MaxNeedsSnacks/FTBQImporter#2]
Hi, I'm trying to import quest from BQM into FTB Quests, but when I run the command in-game, I get the following message: "An unknown error occurred while attempting to perform this command." Looking at the logs, it's saying:

`Couldn't process command: ftbq_import quests
java.lang.NullPointerException: null
	at dev.maxneedssnacks.ftbqimporter.CommandImport.importQuests(CommandImport.java:207) ~[CommandImport.class:?]`

I'm running version 1.0.5 of FTBQImporter, 1.8.0.237 of FTB Quests, and I've tried both 3.5.316 and 3.5.317 of BQM

**Comment by MaxNeedsSnacks** [comment]
Heya, could you send me your Better Questing `default_quests.json`?
Just trying to verify what's wrong here

**Comment by MaxNeedsSnacks** [comment]
I uploaded a new build that might fix your issue, could you try with that one and then get back to me?

**Comment by MaxNeedsSnacks** [comment]
Hey, just wanted to let you know i'm closing this since there's been a new major version released since which has probably fixed your issue in some way.
