### ISSUE TITLE
[Suggestion] Import Quests From Better Questing - Standard Expansion

### ISSUE THREAD

**Issue by TowardtheStars** [MaxNeedsSnacks/FTBQImporter#5]
Could you please add compatibility for [Better Questing - Standard Expansion](https://www.curseforge.com/minecraft/mc-mods/better-questing-standard-expansion)? 

Many useful quest types in that expansion pack such as advancement and mob kills are supported by FTB Quests now. Also, this expansion pack is widely used in many modpacks. So such a feature will be convenient for users.

**Comment by MaxNeedsSnacks** [comment]
Hiya, could you tell me which sorts of concrete task types you'd want to see added to the mod? Both mob kill tasks and advancement tasks *should* already be a thing unless I messed something up with their implementation

**Comment by TowardtheStars** [comment]
Actually, There isn't anything related to "bq_standard:advancement" or "bq_standard:mob_kills" in your code in master branch on GitHub. 

![图片](https://user-images.githubusercontent.com/29396015/71365911-56a5e680-25db-11ea-8ba4-6bbfd1b3073e.png)


Also, location, NPC meeting and fluid retrieval task types in Better Questing - Standard Expansion are also available in FTB Quests, so you might want to add those too.

Other than that, a little restructuring such as using classes and a hash map to read quests from Better Questing and write that to FTB Quests might help you get a clearer view on what you have implemented and what have not. It will be even more convenient for you to debug and to add features.

**Comment by MaxNeedsSnacks** [comment]
Oh, the respective tags for those are "bq_standard:trigger" and "bq_standard:hunt" ^^

Also yeah, I'm already passively "working" on a redesign so things might look a bit better soon than this jumbled mess

As for fluid tasks, unfortunately, FTB Quests only supports tasks that consume the fluid and I don't think there's any way to do NPC meeting tasks in FTB Quests without using external (i.e. KubeJS) scripting, so I'll have to see whether I can implement those

**Comment by TowardtheStars** [comment]
![图片](https://user-images.githubusercontent.com/29396015/71393810-4c223600-2649-11ea-91e3-26912d0ee938.png)
This is an example of advancement type task generated by command "/bqs_advancement_dump" (There should be a subcommand following, but I forget ). It's task id is "bq_standard:advancement", not "bq_standard:trigger".

**Comment by MaxNeedsSnacks** [comment]
Oh that's interesting, I never knew advancements were also a valid task type, I just checked out Better Questing's importer for that and saw that it converts it to a trigger task (see [here](https://github.com/Funwayguy/StandardQuestingPack/blob/1.12/src/main/java/bq_standard/importers/ftbq/converters/tasks/FtbqTaskAdvancement.java)), so I figured that would be the thing I'd have to use that to convert the other way round as well. I'll push out a fix for that soon, thanks ^^

**Comment by MaxNeedsSnacks** [comment]
I fixed advancement tasks and added fluid task support in ecff59ce6971e2d38c96a0ccd8238481c5ef0b0d, let me know if anything else could be imported from Standard Expansion ^^

As for the restyle, that's still going to take a while since I'm busy with celebrating Christmas and studying currently, so for now I'll still be adding things the old way
