### ISSUE TITLE
quest line order

### ISSUE THREAD

**Issue by Spongman** [MaxNeedsSnacks/FTBQImporter#7]
version: forge-1.12.2-1.1.8
modpack: enigmatica 2 lite

the resulting list of quest lines is in a different order. for example, in BQ the first quest line is 'Vanilla & Info', but in FTB that quest line is #8 in the list. all the others are randomly ordered as well.

**Comment by MaxNeedsSnacks** [comment]
hmm i might need to take a look at that, they should actually be sorted by the order they appear in the json

**Comment by MaxNeedsSnacks** [comment]
quick question: does this "random" order change every time you reimport, or is it the same with each import?

(make sure you backup your current quests under `config/ftbquests/normal (i think?)` first and try this in a new world if you want to keep your progress please)
