### ISSUE TITLE
overwrite icons?

### ISSUE THREAD

**Issue by Spongman** [MaxNeedsSnacks/FTBQImporter#8]
version: forge-1.12.2-1.1.8
modpack: enigmatica 2 lite

in this modpack, all the questlines have a Book as the icon. this is fine in BQ because it always lists the quest line name, but in FTB it only shows the icon:

![image](https://user-images.githubusercontent.com/1088194/75634352-f7a7b380-5bc1-11ea-8614-b25942eb1941.png)

could you add an import option that instead uses the first quest icon (eg the 'sapling' icon in the above image) as the quest line icon?

**Comment by MaxNeedsSnacks** [comment]
BQ actually supports questline icons iirc, and those do get imported correctly, it's just that Enigmatica 2 uses books for each chapter so they all look the same ^^
